export const styles = {
  // Lock Screen Styles
  lockScreenContainer: { display: "flex", justifyContent: "center", alignItems: "center", height: "100vh", backgroundColor: "#0f172a", fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" },
  lockCard: { backgroundColor: "#1e293b", padding: "36px", borderRadius: "16px", border: "1px solid #334155", textAlign: "center", width: "360px", boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.5)" },
  lockIcon: { fontSize: "40px", marginBottom: "12px" },
  lockTitle: { color: "#f8fafc", fontSize: "22px", fontWeight: "800", margin: "0 0 6px 0" },
  lockSubtitle: { color: "#94a3b8", fontSize: "13px", margin: "0 0 24px 0" },
  lockForm: { display: "flex", flexDirection: "column", gap: "12px" },
  lockInput: { padding: "12px 14px", borderRadius: "8px", border: "1px solid #475569", backgroundColor: "#0f172a", color: "#fff", fontSize: "14px", outline: "none", textAlign: "center" },
  lockInputError: { padding: "12px 14px", borderRadius: "8px", border: "1px solid #ef4444", backgroundColor: "#0f172a", color: "#fff", fontSize: "14px", outline: "none", textAlign: "center" },
  errorText: { color: "#f87171", fontSize: "12px", margin: "0" },
  lockBtn: { padding: "12px", borderRadius: "8px", border: "none", backgroundColor: "#2563eb", color: "#fff", fontWeight: "700", cursor: "pointer", fontSize: "14px" },

  // Dashboard Styles
  container: { fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", padding: 16, backgroundColor: "#f8fafc", minHeight: "100vh", boxSizing: "border-box", width: "100%" },
  loadingContainer: { display: "flex", justifyContent: "center", alignItems: "center", height: "100vh" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" },
  title: { fontSize: "26px", fontWeight: "800", color: "#0f172a", margin: 0 },
  subtitle: { fontSize: "14px", color: "#64748b", marginTop: "4px", margin: 0 },
  addBtn: { backgroundColor: "#2563eb", color: "#fff", padding: "10px 18px", borderRadius: "8px", border: "none", fontWeight: "600", cursor: "pointer" },
  logoutBtn: { backgroundColor: "#334155", color: "#f8fafc", padding: "10px 14px", borderRadius: "8px", border: "none", fontWeight: "600", cursor: "pointer" },
  metricsGrid: { display: "grid", gridTemplateColumns: "repeat(5, minmax(0, 1fr))", gap: "10px", marginBottom: "16px" },
  metricCard: { backgroundColor: "#fff", padding: "12px 14px", borderRadius: "10px", border: "1px solid #e2e8f0", display: "flex", flexDirection: "column", minWidth: 0 },
  metricLabel: { fontSize: "12px", color: "#64748b", fontWeight: "600" },
  metricValue: { fontSize: "24px", fontWeight: "800", color: "#0f172a", marginTop: "2px" },
  metricSubText: { fontSize: "11px", color: "#94a3b8", marginTop: "2px" },
  filterBar: { display: "flex", gap: "10px", marginBottom: "16px", flexWrap: "wrap" },
  filterBtn: { padding: "8px 14px", borderRadius: "8px", border: "1px solid #cbd5e1", backgroundColor: "#fff", cursor: "pointer", fontSize: "13px" },
  activeFilterBtn: { padding: "8px 14px", borderRadius: "8px", border: "none", backgroundColor: "#2563eb", color: "#fff", fontWeight: "600", cursor: "pointer", fontSize: "13px" },
  tableContainer: { backgroundColor: "#fff", borderRadius: "10px", border: "1px solid #e2e8f0", overflow: "hidden" },
  table: { width: "100%", borderCollapse: "collapse", textAlign: "left" },
  tableHeader: { backgroundColor: "#f8fafc", borderBottom: "1px solid #e2e8f0" },
  th: { padding: "12px 16px", fontSize: "11px", fontWeight: "700", color: "#475569", textTransform: "uppercase" },
  clickableTableRow: { borderBottom: "1px solid #f1f5f9", cursor: "pointer", transition: "background-color 0.15s" },
  td: { padding: "14px 16px", verticalAlign: "middle" },
  memberName: { fontWeight: "600", color: "#0f172a", fontSize: "14px" },
  memberSub: { fontSize: "12px", color: "#64748b" },
  badgePending: { backgroundColor: "#eff6ff", color: "#1d4ed8", padding: "3px 8px", borderRadius: "6px", fontSize: "12px", fontWeight: "600" },
  badgeWeek: { backgroundColor: "#f1f5f9", color: "#334155", padding: "3px 8px", borderRadius: "6px", fontSize: "12px", fontWeight: "600" },
  scanCompleteBadge: { backgroundColor: "#dcfce7", color: "#15803d", padding: "3px 8px", borderRadius: "6px", fontSize: "12px", fontWeight: "600" },
  scanPartialBadge: { backgroundColor: "#f8fafc", color: "#64748b", border: "1px solid #cbd5e1", padding: "3px 8px", borderRadius: "6px", fontSize: "12px", fontWeight: "500" },
  waitingText: { fontSize: "12px", color: "#94a3b8", fontStyle: "italic" },
  matrixGrid: { display: "grid", gridTemplateColumns: "repeat(12, 1fr)", gap: "4px", width: "260px" },
  matrixBox: { width: "18px", height: "22px", borderRadius: "3px", display: "flex", alignItems: "center", justifyContent: "center" },
  matrixText: { fontSize: "10px", fontWeight: "700", color: "#fff" },
  arrowIcon: { fontSize: "16px", color: "#cbd5e1", fontWeight: "bold" },
  
  // Person View Modal Styles
  modalOverlay: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(15, 23, 42, 0.6)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 1000 },
  personViewModal: { backgroundColor: "#fff", borderRadius: "12px", width: "720px", maxWidth: "95%", maxHeight: "90vh", overflowY: "auto", padding: "24px", display: "flex", flexDirection: "column", gap: "16px" },
  personHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", paddingBottom: "12px", borderBottom: "1px solid #e2e8f0" },
  closeBtn: { background: "none", border: "none", fontSize: "20px", cursor: "pointer", color: "#64748b" },
  progressCard: { backgroundColor: "#f8fafc", padding: "12px 16px", borderRadius: "8px", border: "1px solid #e2e8f0" },
  progressBarTrack: { backgroundColor: "#e2e8f0", height: "8px", borderRadius: "4px", overflow: "hidden" },
  progressBarFill: { backgroundColor: "#2563eb", height: "100%", borderRadius: "4px", transition: "width 0.3s ease" },
  personStatsRow: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "10px" },
  personStatBox: { backgroundColor: "#f8fafc", padding: "10px 12px", borderRadius: "8px", border: "1px solid #e2e8f0", display: "flex", flexDirection: "column" },
  personStatLabel: { fontSize: "10px", color: "#64748b", textTransform: "uppercase", fontWeight: "700" },
  personStatValue: { fontSize: "15px", fontWeight: "800", color: "#0f172a", marginTop: "2px" },
  personStatSubText: { fontSize: "10px", color: "#94a3b8", marginTop: "2px" },
  sectionCard: { backgroundColor: "#fff", border: "1px solid #e2e8f0", borderRadius: "8px", padding: "16px" },
  
  // Calendar Styles
  calendarGridContainer: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "12px" },
  calendarMonthCard: { backgroundColor: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "8px", padding: "10px" },
  calendarMonthTitle: { fontSize: "12px", fontWeight: "700", color: "#0f172a", marginBottom: "8px", textAlign: "center" },
  calendarHeaderRow: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: "2px", marginBottom: "4px" },
  calendarHeaderCell: { fontSize: "9px", fontWeight: "700", color: "#64748b", textAlign: "center" },
  calendarDaysGrid: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: "2px" },
  calendarDayEmpty: { height: "26px" },
  calendarDayCell: { position: "relative", height: "26px", borderRadius: "3px", backgroundColor: "#fff", border: "1px solid #e2e8f0", fontSize: "10px", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", color: "#475569" },
  calendarDayVisited: { backgroundColor: "#22c55e", color: "#fff", fontWeight: "bold", border: "none" },
  calendarDayToday: { border: "2px solid #2563eb", fontWeight: "bold" },
  calendarWeekBadge: { position: "absolute", top: "1px", left: "2px", fontSize: "7px", fontWeight: "800", color: "#2563eb", backgroundColor: "#eff6ff", borderRadius: "2px", padding: "0 2px" },

  // Tabs System Styles
  tabHeaderBar: { display: "flex", gap: "6px", borderBottom: "1px solid #e2e8f0", paddingBottom: "10px", marginBottom: "12px", overflowX: "auto" },
  tabBtn: { padding: "6px 12px", borderRadius: "6px", border: "1px solid #cbd5e1", backgroundColor: "#f8fafc", color: "#475569", fontSize: "12px", fontWeight: "600", cursor: "pointer", whiteSpace: "nowrap" },
  tabBtnActive: { padding: "6px 12px", borderRadius: "6px", border: "none", backgroundColor: "#2563eb", color: "#ffffff", fontSize: "12px", fontWeight: "700", cursor: "pointer", whiteSpace: "nowrap" },

  scanBoxDone: { flex: 1, backgroundColor: "#dcfce7", color: "#15803d", border: "1px solid #86efac", padding: "10px", borderRadius: "6px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: "6px", fontWeight: "600", fontSize: "13px" },
  scanBoxPending: { flex: 1, backgroundColor: "#f8fafc", color: "#64748b", border: "1px solid #cbd5e1", padding: "10px", borderRadius: "6px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: "6px", fontWeight: "500", fontSize: "13px" },
  historyLogList: { maxHeight: "180px", overflowY: "auto", display: "flex", flexDirection: "column", gap: "6px" },
  historyLogItem: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "8px 12px", backgroundColor: "#f8fafc", borderRadius: "6px", border: "1px solid #f1f5f9" },
  weekPill: { backgroundColor: "#e0e7ff", color: "#3730a3", padding: "2px 8px", borderRadius: "10px", fontSize: "11px", fontWeight: "700" },
  deleteLogBtn: { background: "none", border: "none", cursor: "pointer", fontSize: "14px", padding: "2px 4px", opacity: 0.8 },
  manualCheckInBtn: { backgroundColor: "#16a34a", color: "#fff", border: "none", padding: "6px 12px", borderRadius: "6px", fontSize: "12px", fontWeight: "600", cursor: "pointer" },
  secondaryBtn: { backgroundColor: "#f1f5f9", color: "#334155", border: "1px solid #cbd5e1", padding: "6px 12px", borderRadius: "6px", fontSize: "12px", cursor: "pointer" },
  deleteBtn: { backgroundColor: "#ef4444", color: "#fff", border: "none", padding: "8px 14px", borderRadius: "6px", fontSize: "12px", fontWeight: "600", cursor: "pointer" },
  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" },
  form: { display: "flex", flexDirection: "column", gap: "10px" },
  label: { fontSize: "11px", fontWeight: "600", color: "#475569" },
  input: { padding: "8px 10px", borderRadius: "6px", border: "1px solid #cbd5e1", width: "100%", boxSizing: "border-box" },
  modalContent: { backgroundColor: "#fff", padding: "24px", borderRadius: "12px", width: "420px", maxWidth: "90%" },
  modalActions: { display: "flex", justifyContent: "flex-end", gap: "10px", marginTop: "16px" },
  saveBtn: { padding: "8px 16px", borderRadius: "6px", backgroundColor: "#2563eb", color: "#fff", border: "none", cursor: "pointer", fontWeight: "600" },
  cancelBtn: { padding: "8px 16px", borderRadius: "6px", backgroundColor: "#e2e8f0", color: "#334155", border: "none", cursor: "pointer" }
};

export function getStyles(dark) {
  if (!dark) return styles;
  return {
    ...styles,
    container: { ...styles.container, backgroundColor: "#0f172a" },
    title: { ...styles.title, color: "#f8fafc" },
    subtitle: { ...styles.subtitle, color: "#94a3b8" },
    metricCard: { ...styles.metricCard, backgroundColor: "#1e293b", borderColor: "#334155" },
    metricLabel: { ...styles.metricLabel, color: "#94a3b8" },
    metricValue: { ...styles.metricValue, color: "#f8fafc" },
    filterBtn: { ...styles.filterBtn, backgroundColor: "#1e293b", borderColor: "#334155", color: "#e2e8f0" },
    tableContainer: { ...styles.tableContainer, backgroundColor: "#1e293b", borderColor: "#334155" },
    tableHeader: { ...styles.tableHeader, backgroundColor: "#0f172a", borderBottom: "1px solid #334155" },
    th: { ...styles.th, color: "#94a3b8" },
    clickableTableRow: { ...styles.clickableTableRow, borderBottom: "1px solid #334155" },
    memberName: { ...styles.memberName, color: "#f8fafc" },
    badgeWeek: { ...styles.badgeWeek, backgroundColor: "#334155", color: "#e2e8f0" },
    scanPartialBadge: { ...styles.scanPartialBadge, backgroundColor: "#0f172a", color: "#94a3b8", borderColor: "#475569" },
  };
}